### ISSUE TITLE
Pressing "STOP" stage button when running "Continuous" mode in `aslm -sh` on a Mac causes crash

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/navigate#356]
Super weird. Traceback follows.

```
Traceback (most recent call last):
  File "/Users/zachmarin/opt/miniconda3/envs/ASLM/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/zachmarin/opt/miniconda3/envs/ASLM/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/zachmarin/Code/ASLM/src/aslm/model/model.py", line 657, in run_data_process
    self.show_img_pipe.send(frame_ids[0])
  File "/Users/zachmarin/opt/miniconda3/envs/ASLM/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/zachmarin/opt/miniconda3/envs/ASLM/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/Users/zachmarin/opt/miniconda3/envs/ASLM/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by zacsimile** [comment]
This comes from setting the position of the stages to an invalid value by pressing "Stop Stage". This can only happen if the stage is moving outside of its set range and this button is pressed. This is possible in synthetic mode, but unlikely to show up in real life.

It can also produce the error

```
objc[66028]: Invalid or prematurely-freed autorelease pool 0x13586a0b0. Set a breakpoint on objc_autoreleasePoolInvalid to debug. 
objc[66028]: Invalid autorelease pools are a fatal error
```

I believe this is a tkinter bug (see https://bugs.python.org/issue34313) and outside of our scope of problems to fix.

**Comment by AdvancedImagingUTSW** [comment]
I took a look at this and no longer could repeat the error. As you can see in my view_controller_debug file, images continue to be received after hitting the stop stage button.

[view_controller_debug.log](https://github.com/TheDeanLab/navigate/files/15279525/view_controller_debug.log).

Will proceed to close issue but keep an eye out for it in the future.
